service: Jobfinderrz

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-1'
  memorySize: 128
  timeout: 600

functions:
  mainfunction:
    handler: src/handler.handler
    events:
      - httpApi:
          method: get
          path: /findjob

environment:

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: JobsTable
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
          - AttributeName: description
            AttributeType: S
          - AttributeName: company
            AttributeType: S
        KeySchema:
          - AttributeName: description
            KeyType: HASH
          - AttributeName: company
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
  
plugins:
  - serverless-plugin-typescript
  - serverless-offline