service: Jobfinderrz

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'
  memorySize: 512
  timeout: 600
  iam:
    role: arn:aws:iam::693609258176:role/JobFinderrz_Role

functions:
  mainfunction:
    handler: src/handler.handler
    events:
      - httpApi:
          method: get
          path: /findjob

environment:

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: JobsTable
        AttributeDefinitions:
          - AttributeName: description
            AttributeType: S
          - AttributeName: company
            AttributeType: S
        KeySchema:
          - AttributeName: description
            KeyType: HASH
          - AttributeName: company
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-offline
